---
- name: Install Network and Share Tools
  pacman:
    name:
      - tailscale
      - nfs-utils
      - cifs-utils
      - avahi
      - nss-mdns
    state: present

- name: Enable Avahi for .local mDNS resolution
  systemd:
    name: avahi-daemon
    enabled: yes
    state: started

- name: Enable and start Tailscale service
  systemd:
    name: tailscaled
    enabled: yes
    state: started

- name: Enable and start NordVPN service
  systemd:
    name: nordvpnd
    enabled: yes
    state: started

- name: Configure Split Tunneling for local network and Tailscale in NordVPN
  shell: |
    nordvpn whitelist add subnet 100.64.0.0/10
    nordvpn whitelist add subnet 192.168.2.0/24
  register: nord_whitelist
  changed_when: "'is already in the whitelist' not in nord_whitelist.stdout"
  failed_when: false
  ignore_errors: yes
