---
- name: Install Network and Share Tools
  pacman:
    name:
      - tailscale
      - nfs-utils
      - cifs-utils
      - avahi
      - nss-mdns
    state: present

- name: Enable Avahi for .local mDNS resolution
  systemd:
    name: avahi-daemon
    enabled: yes
    state: started

- name: Enable and start Tailscale service
  systemd:
    name: tailscaled
    enabled: yes
    state: started

- name: Enable and start NordVPN service
  systemd:
    name: nordvpnd
    enabled: yes
    state: started

- name: Configure Split Tunneling for local network and Tailscale in NordVPN
  shell: |
    nordvpn whitelist add subnet 100.64.0.0/10
    nordvpn whitelist add subnet {{ local_subnet }}
  register: nord_whitelist
  changed_when: "'is already in the whitelist' not in nord_whitelist.stdout"
  failed_when: false
  ignore_errors: yes

- name: Check if mount points exist
  stat:
    path: "/mnt/unraid_{{ item.name | lower | replace(' ', '_') }}"
  loop:
    - { name: 'Back Ups' }
    - { name: 'Documents' }
    - { name: 'Media' }
    - { name: 'Pictures' }
  register: mount_points_stat

- name: Create mount points for Unraid shares
  file:
    path: "/mnt/unraid_{{ item.name | lower | replace(' ', '_') }}"
    state: directory
    mode: '0755'
  loop:
    - { name: 'Back Ups' }
    - { name: 'Documents' }
    - { name: 'Media' }
    - { name: 'Pictures' }
  loop_control:
    index_var: idx
  when: not mount_points_stat.results[idx].stat.exists

- name: Mount Unraid shares
  mount:
    path: "/mnt/unraid_{{ item.name | lower | replace(' ', '_') }}"
    src: "{{ unraid_ip }}:/mnt/user/{{ item.name }}"
    fstype: nfs
    opts: rw,noatime,nofail,x-systemd.automount,x-systemd.idle-timeout=600
    state: mounted
  loop:
    - { name: 'Back Ups' }
    - { name: 'Documents' }
    - { name: 'Media' }
    - { name: 'Pictures' }

- name: Ensure GNOME bookmarks for mounts
  lineinfile:
    path: "/home/{{ user_id }}/.config/gtk-3.0/bookmarks"
    line: "file://{{ item.path }} {{ item.label }}"
    create: yes
    owner: "{{ user_id }}"
    group: "{{ user_id }}"
    mode: '0644'
  loop:
    - { path: '/mnt/unraid_back_ups', label: 'Unraid Back Ups' }
    - { path: '/mnt/unraid_documents', label: 'Unraid Documents' }
    - { path: '/mnt/unraid_media', label: 'Unraid Media' }
    - { path: '/mnt/unraid_pictures', label: 'Unraid Pictures' }
    - { path: '/mnt/games', label: 'Games' }
    - { path: '/mnt/storage', label: 'Storage' }
